myyrakle/rupring

Cargo.toml
rupring/Cargo.toml
rupring/src/lib.rs
rupring_example/Cargo.toml
rupring_example/src/main.rs
src/lib.rs

[#1] refactoring to workspace structure

---

rupring/src/boot/mod.rs
rupring/src/boot/route.rs

[#8] impl: is_route_matching_request

---

rupring/src/boot/route.rs

[#11] normalize path 구현

---

rupring/src/boot/mod.rs
rupring/src/lib.rs

[#18] impl header conversion

---

rupring/src/boot/mod.rs
rupring/src/boot/parse.rs
rupring/src/boot/route.rs
rupring/src/lib.rs

[#14] impl parse_path_parameter

---

rupring/Cargo.toml
rupring/src/boot/mod.rs
rupring/src/boot/route.rs
rupring/src/lib.rs
rupring/src/main.rs
test.http

[#21] impl request body forwarding

---

rupring/src/boot/mod.rs
rupring/src/lib.rs

[#23] impl response status/header forward

---

rupring/src/lib.rs
rupring/src/response.rs
rupring_macro/src/lib.rs

[#29] seperate Response, add IntoResponse

---

README.md
rupring/Cargo.toml
rupring/src/boot/di.rs
rupring/src/boot/mod.rs
rupring/src/lib.rs
rupring/src/main.rs
rupring/src/request.rs
rupring_macro/src/lib.rs

[#34] DI 기본 기능 구현 

---

README.md
rupring/Cargo.toml
rupring/src/lib.rs
rupring/src/main.rs
rupring/src/response.rs

[#40] Response 타입 리팩토링

---

rupring/src/boot/mod.rs
rupring/src/lib.rs
rupring/src/main.rs
rupring/src/request.rs

[#43] recover panic case

---

README.md
rupring/Cargo.toml
rupring/src/boot/di.rs
rupring/src/boot/mod.rs
rupring/src/boot/route.rs
rupring/src/lib.rs
rupring/src/main.rs
rupring/src/request.rs
rupring/src/response.rs
rupring_macro/Cargo.toml
rupring_macro/src/lib.rs

[#37] 미들웨어 구현 

---

rupring/src/lib.rs
rupring_macro/src/lib.rs

[#49] *Mapping alias 추가 

---

rupring/src/lib.rs
rupring/src/main.rs
rupring/src/response.rs

[#47] 리다이렉트 메서드 구현 

---

README.md
rupring/Cargo.toml
rupring/src/boot/banner.rs
rupring/src/boot/mod.rs
rupring/src/lib.rs
rupring/src/logger/mod.rs
rupring/src/main.rs

[#31] 기본 로깅 설정 

---

README.md
rupring/Cargo.toml
rupring/src/boot/route.rs
rupring/src/main.rs
rupring_macro/Cargo.toml
rupring_macro/src/parse.rs

[#59] path 파싱 버그 수정 

---

rupring/src/boot/route.rs
rupring/src/main.rs
rupring_macro/src/lib.rs

[#35]  Controller attribute macro => routes에서 function scope도 포워딩하도록 개선

---

rupring/src/boot/route.rs

[#12] find_route 테스트케이스 작성

---

rupring/Cargo.toml
rupring/src/boot/mod.rs
rupring/src/header.rs
rupring/src/lib.rs
rupring/src/main.rs

[#55] request-id 주입기능 추가

---

README.md
rupring/Cargo.toml
rupring/src/lib.rs
rupring/src/main.rs
rupring_macro/Cargo.toml
rupring_macro/src/lib.rs
rupring_macro/src/parse.rs
test.http

[#63] Injectable 매크로 구현

---

rupring/src/lib.rs
rupring/src/main.rs
rupring_macro/src/lib.rs

[#68] Injectable 어노테이션에 name 추가

---

rupring/src/boot/mod.rs
rupring/src/swagger/context.rs
rupring/src/swagger/json.rs
rupring/src/swagger/module.rs
rupring/src/swagger/routes.rs
rupring_macro/src/lib.rs

[#76] Swagger Path 단위 생성 구현

---

rupring/src/boot/route.rs
rupring/src/lib.rs
rupring/src/main.rs
rupring/src/meme.rs
rupring/src/response.rs
rupring/src/swagger/routes.rs

[#52] 코드 리팩토링 

---

rupring/src/lib.rs
rupring/src/main.rs
rupring/src/swagger/context.rs
rupring/src/swagger/mod.rs
rupring_macro/src/lib.rs
rupring_macro/src/parse.rs

[#81] summary, description 생성 기능 구현

---

rupring/src/main.rs
rupring/src/swagger/context.rs
rupring/src/swagger/json.rs
rupring_macro/src/lib.rs

[#83] swagger: tags 생성 기능 구현

---

rupring/src/main.rs
rupring_macro/src/lib.rs
rupring_macro/src/parse.rs

[#88] PathVariable 관련 리팩토링

---

rupring/src/main.rs
rupring_macro/src/lib.rs
rupring_macro/src/parse.rs
test.http

[#92] description 어노테이션 기능 개선

---

README.md
rupring/Cargo.toml
rupring/src/lib.rs
rupring/src/main.rs
rupring_macro/Cargo.toml
rupring_macro/src/parse.rs

[#95] 0.7.0 배포준비

---

README.md
rupring/Cargo.toml
rupring/src/lib.rs
rupring/src/main.rs
rupring_macro/Cargo.toml
rupring_macro/src/lib.rs

[#98] v0.7.1

---

rupring/src/example/domains/users/dto.rs
rupring/src/swagger/json.rs
rupring_macro/src/lib.rs

[#115] example 문서화 기능 구현

---

rupring/src/example/domains/users/controller.rs
rupring/src/example/domains/users/dto.rs
rupring/src/example/main.rs
rupring/src/swagger/macros.rs
rupring_macro/src/lib.rs

[#118] required 문서화 옵션 구현

---

rupring/src/example/domains/users/dto.rs
rupring_macro/src/lib.rs

[#117] description 문서화 기능 구현

---

rupring/src/example/domains/users/dto.rs
rupring_macro/src/lib.rs

[#119] RupringDoc name 문서화 기능 구현

---

rupring/src/example/domains/users/controller.rs
rupring/src/example/domains/users/dto.rs
rupring/src/lib.rs
rupring/src/swagger/context.rs
rupring_macro/src/lib.rs

[#85] Response 문서화 기능 구현

---

rupring/src/example/domains/users/controller.rs
rupring/src/lib.rs
rupring/src/swagger/context.rs
rupring/src/swagger/json.rs
rupring_macro/src/attribute.rs
rupring_macro/src/lib.rs

resolves: #93
일단 BearerAuth만 구현

[#93] auth attribute 구현

---

rupring/src/example/domains/users/controller.rs
rupring/src/example/domains/users/dto.rs
rupring/src/request.rs
rupring_macro/src/lib.rs

[#133] request bind 패닉케이스 수정, query bind 오류 개선

---

rupring/src/boot/di.rs

[#131] 불필요한 UnwindSafe impl 제거

---

rupring_macro/src/lib.rs
rupring_macro/src/rule.rs

I follow tutorial, but i get an warning on this example
fix MapRoute, RupringDoc, Injectable macro

fix: RouteName and Handler Name shoulde be camel case because this is struct

---

application.properties
rupring/Cargo.toml
rupring/src/application_properties.rs
rupring/src/core/boot.rs
rupring/src/core/mod.rs
rupring/src/header.rs
rupring/src/lib.rs
rupring/src/response.rs

resolves: #144
gzip 기반의 응답 압축 옵션 추가, 약간의 리팩토링

[#144] 응답 압축 구현

---

rupring_example/Cargo.toml

resolves: #151
현재 실행경로에서만 로드하는건 컨테이너 말아쓰기 불편할거같아서 추가함

[#151] application.properties 탐색 경로 추가 

---

rupring/src/application_properties.rs
rupring/src/lib.rs

[#149] application.properties 문서화 

---

rupring/src/application_properties.rs
rupring/src/core/mod.rs

[#154] deflate 압축 옵션 구현 

---

application.properties
rupring/Cargo.toml
rupring/src/application_properties.rs
rupring/src/core/graceful.rs
rupring/src/core/mod.rs

[#143] graceful shutdown 구현

---

rupring/src/application_properties.rs
rupring_example/Cargo.toml

resolves: #156
이제는 환경변수 기반으로도 설정값을 활성화할 수 있음. (적용되는 우선순위는 .properties보다 낮음)

[#156] 환경변수에서도 application.properties 값 추출

---

README.md
rupring/Cargo.toml
rupring/src/lib.rs
rupring/src/swagger/mod.rs
rupring_example/src/domains/users/dto.rs
rupring_macro/Cargo.toml
rupring_macro/src/lib.rs

resolves: #163
용도를 명확하게 가리키기 위한 단순 이름 변경

[#163] rename RupringDoc => RupringDto

---

rupring/src/application_properties.rs
rupring/src/core/mod.rs
rupring/src/core/parse.rs
rupring/src/core/route.rs

[#150] CompressionAlgorithm 정의

---

rupring/src/application_properties.rs
rupring/src/core/boot.rs
rupring/src/lib.rs

[#166] 코어/스레드 수 조정 기능 추가

---

rupring_example/Cargo.toml
rupring_example/src/domains/users/dto.rs
rupring_example/src/domains/users/interface.rs
rupring_example/src/domains/users/model.rs
rupring_example/src/domains/users/service.rs

resolves: #38
테스트 전용 구성이 필요할까 싶어서 짜봤는데, 딱히 필요없을 것 같음.
예제 코드에만 기본적인 코드 작성 형태를 추가해둠

[#38] example에 테스트케이스 추가

---

.gitignore
.vscode/settings.json
rupring_example/Cargo.toml
rupring_example/Dockerfile
rupring_example/README.md
rupring_example/application.properties

[#170] Docker 예제 추가

---

.gitignore
README.md
application.properties
rupring/Cargo.toml
rupring/src/core/boot.rs
rupring/src/core/bootings/aws_lambda.rs
rupring/src/core/bootings/mod.rs
rupring/src/core/compression.rs
rupring/src/core/graceful.rs
rupring/src/core/mod.rs
rupring/src/lib.rs
rupring/src/utils/hyper.rs
rupring/src/utils/mod.rs
rupring_example/Cargo.toml
rupring_example/README.md
rupring_example/src/lambda.rs
rupring_example/src/main.rs

resolves: #147
서버를 AWS Lambda에 바로 올려서 사용할 수 있는 옵션 구현

[#147] AWS Lambda용 부팅 옵션 추가

---

rupring/src/core/boot.rs
rupring/src/core/bootings/aws_lambda.rs
rupring/src/core/mod.rs
rupring/src/lib.rs

[#176] aws-lambda 에러 핸들링 개선

---

rupring/src/core/bootings/aws_lambda.rs
rupring/src/core/mod.rs

[#180] aws-lambda에 이벤트루프 적용

---

.gitignore
README.md
rupring/Cargo.toml
rupring/src/core/bootings/aws_lambda.rs
rupring/src/core/mod.rs

[#178] 누락된 부분 구현

---

rupring_example/src/domains/users/controller.rs

resolves: #184
딱히 버그같은건 아니었고, 오류처리 애매하게 해놔서 헷갈린거였음

[#184] 예제 코드 수정

---

rupring/src/core/mod.rs
rupring/src/lib.rs

[#186] run_server 반환타입을 anyhow로 변경

---

rupring/src/application_properties.rs
rupring/src/core/banner.rs
rupring/src/core/mod.rs
rupring_example/Cargo.toml
rupring_example/application.properties

resolves: #172
배너 비활성화, 배너 커스텀 동작 구현

[#172] 배너 관련 기능 재작성 

---

rupring/Cargo.toml
rupring/src/application_properties.rs
rupring/src/core/mod.rs
rupring/src/lib.rs
rupring_example/application.properties
rupring_example/src/domains/root/controller.rs

[#174] request-timeout 옵션 구현

---

rupring/src/core/mod.rs
rupring/src/request.rs

[#200] cookies 필드 추가 및 파싱 구현

---

.github/workflows/clippy.yml
rupring_example/src/domains/users/service.rs

[#211] clippy workflow 추가

---

rupring/src/request.rs
rupring/src/swagger/context.rs
rupring/src/test_proc_macro/injectable.rs
rupring_macro/src/lib.rs

[#214] clippy: 불필요한 return 제거

---

rupring/src/header.rs
rupring/src/request.rs
rupring/src/response.rs
rupring_example/src/domains/root/controller.rs

[#216] Response::download 함수 구현

---

rupring/src/core/mod.rs
rupring/src/core/multipart.rs
rupring/src/lib.rs
rupring/src/request.rs
rupring_example/src/domains/root/controller.rs

[#157] 멀티파트 파싱 구현

---

rupring/src/response.rs
rupring_example/src/domains/root/controller.rs

[#222] Response::html 숏컷 함수 구현

---

rupring/src/application_properties.rs
rupring/src/core/mod.rs
rupring/src/core/multipart.rs
rupring/src/request.rs
rupring_example/application.properties

[#228] 멀티파트 파싱 관련 옵션 추가

---

rupring/src/application_properties.rs
rupring/src/core/mod.rs
rupring/src/request.rs
rupring_example/application.properties

[#238] 헤더 사이즈 제한 기능

---

rupring/src/application_properties.rs
rupring/src/core/bootings/aws_lambda.rs
rupring/src/core/error_handler.rs
rupring/src/core/mod.rs
rupring/src/request.rs

[#239] request에 메타데이터 필드 추가

---

rupring/src/application_properties.rs
rupring/src/core/error_handler.rs
rupring/src/core/mod.rs
rupring_example/application.properties

[#233] body limit 기능 구현

---

rupring/Cargo.toml
rupring/src/application_properties.rs
rupring/src/core/error_handler.rs
rupring/src/core/mod.rs
rupring_example/Cargo.toml

[#244] request body limit 기능 개선

---

rupring/src/core/error_handler.rs
rupring/src/core/mod.rs

resolves: #247
일반 부팅 모드에 있던 것을 aws-lambda에도 동일하게 동작 구현

[#247] aws-lambda: 413 처리 구현

---

.github/workflows/clippy.yml
rupring/Cargo.toml
rupring/src/application_properties.rs
rupring/src/core/bootings/tls.rs
rupring/src/core/mod.rs
rupring/src/core/multipart.rs
rupring/src/request.rs
rupring_example/application.properties
rupring_example/src/domains/users/repository.rs

[#257] http2 기능 제거

---

rupring/src/core/error_handler.rs
rupring/src/core/mod.rs
rupring/src/response.rs

[#266] Response 구조를 일반화, 기타 코드 재작성

---

rupring/Cargo.toml
rupring/src/core/adapter.rs
rupring/src/core/mod.rs
rupring/src/core/stream.rs
rupring/src/response.rs

[#269] hyper 관련 모듈 버전을 원본으로 교체

---

rupring/Cargo.toml
rupring/src/core/mod.rs
rupring/src/core/stream.rs
rupring/src/response.rs
rupring_example/Cargo.toml
rupring_example/application.properties
rupring_example/src/domains/users/controller.rs

[#272] stream 전송 구현

---

rupring/src/lib.rs

[#262] docs: sse
